version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ia-adm
    volumes:
      - .:/app
    command: python TESTE/teste.py
    restart: unless-stopped
